// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  generalSidebar: [
    {
      type: 'category',
      label: 'General Documentation',
      collapsed: false,
      items: [
        'general/whatistiptop',
        'general/howdoestiptopwork',
        'general/whatcanitbeusedfor',
        'general/installation',
      ],
    },
  ],

  tipTopSidebar: [
    {
      type: 'link',
      label: 'Astro-TipTop Features',
      href: '/astro-tiptop-services/astro_tiptop_modules',
    },
    {
      type: 'category',
      label: 'TipTop | Core Functionality',
      items: [
        'orion/overview',
        'orion/usage',
        'orion/howtosetuplaunchfile',
        'orion/howtosetup',
        'orion/aoinstruments',
        'orion/interactivetools',
        'orion/useful_scripts',
        'orion/parameterfiles',
      ],
    },
    {
      type: 'category',
      label: 'TipTop | Asterism selection',
      items: ['aquila/overview'],
    },
    {
      type: 'category',
      label: 'TipTop | PSF Fitting / PSF Extrapolation',
      items: ['lyra/overview'],
    },
    {
      type: 'category',
      label: 'TipTop | PSF-R Service',
      items: ['phoenix/overview'],
    },
  ],

  // resourcesSidebar: [
  //   {
  //     type: 'link',
  //     label: 'About us',
  //     href: '/resources/about_us'
  //   },
  //   {
  //     type: 'link',
  //     label: 'Contact',
  //     href: '/resources/contact'
  //   },
  // ],

};

export default sidebars;
