// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  generalSidebar: [
    {
      type: 'category',
      label: 'General',
      collapsed: false,
      items: [
        'general/whatistiptop',
        'general/whatcanitbeusedfor',
        'general/howdoestiptopwork',
        'general/error_breakdown',
        'general/installation',
      ],
    },
  ],

  tipTopSidebar: [
    // {
    //   type: 'link',
    //   label: 'Astro-TipTop Features',
    //   href: '/astro-tiptop-services/astro_tiptop_modules',
    // },
    {
      type: 'category',
      label: 'AO PSF Simulation',
      items: [
        'orion/overview',
        'orion/usage',
        'orion/parameterfiles',
        'orion/howtosetup',
        'orion/howtosetuplaunchfile',
        'orion/aoinstruments',
        'orion/useful_scripts',
        'orion/api_reference',
      ],
    },
  ],

  appliSidebar: [
    {
      type: 'link',
      label: 'Applications',
      href: '/astro-tiptop-services/astro_tiptop_modules',
    },
    {
      type: 'category',
      label: 'Asterism selection',
      items: ['aquila/overview',
            'aquila/parameterfiles',
            'aquila/running_selection',
            'aquila/heuristic_models',
            'aquila/tuto_ast_select'
      ],
    },
    {
      type: 'category',
      label: 'Click & Fit',
      items: ['lyra/overview'],
    },
    {
      type: 'category',
      label: 'PSF Reconstruction',
      items: ['phoenix/overview'],
    },
  ],

};

export default sidebars;
