// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  generalSidebar: [
    {
      type: 'category',
      label: 'General Documentation',
      collapsed: false,
      items: [
        'general/whatistiptop',
        'general/howdoestiptopwork',
        'general/whatcanitbeusedfor',
        'general/installation',
      ],
    },
  ],

  tipTopSidebar: [
    {
      type: 'category',
      label: 'Astro-TipTop | Orion',
      items: [
        'orion/overview',
        'orion/usage',
        'orion/parameterfields',
        'orion/howtosetup',
        'orion/examples',
        'orion/api_reference',
      ],
    },
    {
      type: 'category',
      label: 'AstroTipTop | Aquila',
      items: ['aquila/overview'],
    },
    {
      type: 'category',
      label: 'AstroTipTop | Lyra',
      items: ['lyra/overview'],
    },
    {
      type: 'category',
      label: 'AstroTipTop | Phoenix',
      items: ['phoenix/overview'],
    },
  ],

  resourcesSidebar: [
    {
      type: 'link',
      label: 'About us',
      href: '/resources/about_us'
    },
    {
      type: 'link',
      label: 'Contact',
      href: '/resources/contact'
    },
  ],

};

export default sidebars;
