import React from 'react';
import Layout from '@theme/Layout';

export default function TermsPage() {
  return (
    <Layout title="Terms & Conditions for web pages under astro-tiptop-services.github.io/astro-tiptop-services">
      <main className="container margin-vert--xl">
        <h1>Terms & Conditions</h1>
        <p><i>Last updated: June 2025</i></p>
        <p>
          Welcome to Astro-TipTop Services website (the “Site”), operated by the Astro-TipTop-Services project team.
          By accessing or using this Site, you agree to comply with and be bound by the following terms and conditions (“Terms”).
        </p>
          
          
        <section>
          <h2>1. Use of the Site</h2>
            <ul>
              <li> The Site provides access to documentation, downloadable files, interactive tools, a contact form, and a newsletter 
              subscription related to the TipTop software and related services.</li>
              <li> The Site is intended for a general audience, with a focus on astronomers and researchers.</li>
              <li> You agree to use the Site only for lawful purposes and in a way that does not infringe the rights of others or restrict their use of the Site.</li>
            </ul>
        </section>

        <section>
          <h2>2. Intellectual Property Rights</h2>
            <ul>
              <li> All content and code on this Site, including text, graphics, logos, and software, are the property of the Astro-TipTop-Services team or 
                its licensors, unless otherwise stated.</li>
              <li> You may not copy, reproduce, modify, or distribute any part of the Site content without prior written permission.</li>
              <li> However, files and outputs generated and made available for download through the Site may be used freely unless explicitly restricted.</li>
            </ul>
          </section>

          <section>
            <h2>3. User Data and Privacy</h2>
              <ul>
            <li> We collect personal data only when you voluntarily submit information through forms on the Site 
            (e.g., contact form, newsletter subscription).</li>
            <li> Your data will be processed in accordance with our Privacy Policy.</li>
            <li> By submitting your information, you consent to our use of your data for the purposes described.</li>
            </ul>
          </section>

          <section>
            <h2>4. Disclaimer of Warranties and Limitation of Liability</h2>
              <ul>
                <li> The Site and its contents are provided “as is” without warranties of any kind, either express or implied.</li>
                <li>We do not guarantee the accuracy, completeness, or timeliness of the information provided.</li>
                <li> We are not liable for any damages arising from your use of the Site, including but not limited to direct, indirect, incidental, 
                  or consequential damages.</li>
                <li>Use of any files or outputs generated by the Site is at your own risk.</li>
            </ul>
          </section>

          <section>
            <h2>5. Prohibited Conduct</h2>
              <ul>
                <li>You agree not to use the Site to engage in any unlawful activity or to transmit harmful, offensive, or abusive content.</li>
                <li>Unauthorized attempts to access restricted areas or interfere with Site operations are prohibited.</li>
            </ul>
          </section>

          <section>
            <h2>6. External Links</h2>
              <ul>
               <li>The Site may contain links to third-party websites, including the official TipTop software repository. 
                We do not endorse or assume responsibility for these external sites.</li>
             </ul>
          </section>

          <section>
            <h2>7. Changes to the Terms</h2>
              <ul>
            <li> We reserve the right to modify these Terms at any time without prior notice.</li>
            <li> Continued use of the Site after changes constitutes acceptance of the updated Terms.</li>
            </ul>
          </section>

          <section>
            <h2>8. Contact Us</h2>
            <p>
             For questions or concerns regarding these Terms, please contact us via the Site’s contact form or at: astro.tiptop.services@gmail.com.
            </p>
          </section>
        
          <p>
          Some visual assets were generated using AI tools such as GitHub Copilot. These images are provided for illustrative purposes and do not depict real people, places, or events.
          </p>

      </main>
    </Layout>
  );
}
