# GNAO narrow-field mode
[telescope]
TelescopeDiameter = 7.9
ZenithAngle = 30
ObscurationRatio = 0.1646
Resolution = 128
PathPupil = "ELT_pup.fits"
PathStaticOn = 'CombinedError_Wavefront_nm.fits'
PathApodizer = ''
PathStatModes = ''
PupilAngle = 0.0
TechnicalFoV = 120
jitter_FWHM = 0.0
extraErrorNm = 0
extraErrorExp = -2
extraErrorMin = 0

[atmosphere]
Wavelength = 5e-07
Seeing = 0.5544758064516129
L0 = 30.0
Cn2Weights = [0.455, 0.1295, 0.0442, 0.0506, 0.1167, 0.0926, 0.1107]
Cn2Heights = [0, 500.0, 1000, 2000, 4000, 8000, 16000]
WindSpeed = [5.6, 5.77, 6.25, 7.57, 13.31, 19.06, 12.14]
WindDirection = [190, 255, 270, 350, 17, 29, 66]

[sources_science]
Wavelength = [2.179e-06]
Zenith = [0]
Azimuth = [0]

[sources_HO]
Wavelength = 5.89e-07
Zenith = [10, 10, 10, 10]
Azimuth = [45, 135, 225, 315]
Height = 90000.0

[sources_LO]
Wavelength = 7e-07
Zenith = [0.0]
Azimuth = [0.0]

[sensor_science]
PixelScale = 14.223146677215187
FieldOfView = 240
Binning = 1
NumberPhotons = [1500]
SpotFWHM = [[0.0, 0.0, 0.0]]
SpectralBandwidth = 0.0
Transmittance = [1.0]
Dispersion = [[0.0], [0.0]]
SigmaRON = [1.0]
Dark = 0.0
SkyBackground = 1.0
Gain = 1.0
ExcessNoiseFactor = 1.0

[sensor_HO]
WfsType = 'Shack-Hartmann'
Modulation = None
PixelScale = 830
FieldOfView = 240
Binning = 1
NumberPhotons = [384, 384, 384, 384]
SpectralBandwidth = 0.0
Transmittance = [1.0]
Dispersion = [[0.0], [0.0]]
SigmaRON = 0.5
Dark = 0.0
SkyBackground = 0.0
Gain = 1.0
ExcessNoiseFactor = 1.31
NumberLenslets = [25, 25, 25, 25]
NoiseVariance = [None]
Algorithm = 'wcog'
WindowRadiusWCoG = 6
ThresholdWCoG = 0.0
NewValueThrPix = 0.0
addMcaoWFsensConeError = False

[sensor_LO]
PixelScale = 250.0
FieldOfView = 4
Binning = 1
NumberPhotons = [np.float64(8567160.0)]
SpotFWHM = [[0.0, 0.0, 0.0]]
SigmaRON = 0.5
Dark = 0.0
SkyBackground = 0.0
Gain = 1.0
ExcessNoiseFactor = 1.3
NumberLenslets = [1]
Algorithm = 'wcog'
WindowRadiusWCoG = 4
ThresholdWCoG = 0.0
NewValueThrPix = 0.0
noNoise = False
filtZernikeCov = False

[DM]
NumberActuators = [26]
DmPitchs = [0.24]
InfModel = 'gaussian'
InfCoupling = [0.3]
DmHeights = [0.0]
OptimizationZenith = [0]
OptimizationAzimuth = [0]
OptimizationWeight = [1]
OptimizationConditioning = 100.0
NumberReconstructedLayers = 7
AoArea = 'circle'

[RTC]
LoopGain_LO = 'optimize'
LoopGain_HO = 0.5
SensorFrameRate_HO = 500.0
LoopDelaySteps_HO = 2
SensorFrameRate_LO = 1000
LoopDelaySteps_LO = 2

